backend = "glx";
vsync = "opengl-swc";

glx-copy-from-front = true;
glx-swap-method = 2;

xrender-sync-fence = true;

shadow = true;

shadow-radius = 7;
shadow-offset-x = -7;

shadow-offset-y = -7;

shadow-exclude = [
  "name = 'Notification'",
  "class_g = 'dunst'",
  "class_g = 'Conky'",
  "class_g = 'Rofi'",
  "class_g ?= 'Notify-osd'",
  "class_g = 'Cairo-clock'",
  "_GTK_FRAME_EXTENTS@:c"
];

# ---
# Fade
# ---

fading = true
fade-in-step = 0.1;
fade-out-step = 0.1;

# ---
# Opacity
# ---

inactive-opacity-override = false;

# ---
# Settings
# ---

wintypes:
{
  dock = { shadow = false; fading = false; }
  dnd = { shadow = true; }
  popup_menu = { opacity = 0.8; }
  dropdown_menu = { opacity = 0.8; }
};

# ---
# Corners
# ---

corner-radius = 5
round-borders = 5
